# Generated by Django 4.0.5 on 2022-07-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(upload_to='dog/images/'),
        ),
    ]
